server.port =8081
spring.datasource.url=jdbc:mysql://root:KwKzJGyvAhRYhClGNSSeyvRqVQsIqBkJ@shuttle.proxy.rlwy.net:28461/railway
spring.datasource.username=railway
spring.datasource.password=KwKzJGyvAhRYhClGNSSeyvRqVQsIqBkJ

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


spring.security.user.name =elvis
Spring.security.user.password =123